mesh_files:
  sensor:
    visual:
      mesh: "package://robotiq_description/meshes/robotiq_ft_300/visual/ft_300.dae"
      material:
        name: "" 
        color: "0.79216 0.81961 0.93333 1"
    collision:
      mesh: "package://robotiq_description/meshes/robotiq_ft_300/collision/bbox/ft_300.stl"
